(()=>{const h=document.getElementById('site-header'),t=document.getElementById('menu-toggle'),solid=h.hasAttribute('data-solid')||!document.querySelector('.hero'),update=()=>h.classList.toggle('is-scrolled',solid||window.scrollY>30);update();window.addEventListener('scroll',update,{passive:true});t.addEventListener('click',()=>{const o=h.classList.toggle('menu-open');document.body.classList.toggle('menu-open',o);t.setAttribute('aria-expanded',String(o));t.setAttribute('aria-label',o?'Cerrar menú':'Abrir menú')});document.querySelectorAll('#mobile-menu a').forEach(a=>a.addEventListener('click',()=>{h.classList.remove('menu-open');document.body.classList.remove('menu-open');t.setAttribute('aria-expanded','false');t.setAttribute('aria-label','Abrir menú')}));

const ICON=(d)=>'<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="'+d+'"/></svg>';
let lb=null,lbImg,lbCount,lbList=[],lbIdx=0,lbPrevFocus=null;
const lbShow=()=>{lbImg.src=lbList[lbIdx].src;lbImg.alt=lbList[lbIdx].alt;lbCount.textContent=lbList.length>1?(lbIdx+1)+' / '+lbList.length:''};
const lbStep=(d)=>{if(lbList.length<2)return;lbIdx=(lbIdx+d+lbList.length)%lbList.length;lbShow()};
const lbClose=()=>{if(!lb)return;lb.classList.remove('is-open');document.body.classList.remove('lb-open');if(lbPrevFocus)lbPrevFocus.focus()};
const lbBuild=()=>{lb=document.createElement('div');lb.className='lightbox';lb.setAttribute('role','dialog');lb.setAttribute('aria-modal','true');lb.setAttribute('aria-label','Foto ampliada');lb.innerHTML='<button type="button" class="lb-close" aria-label="Cerrar foto">'+ICON('M6 6l12 12M18 6L6 18')+'</button><button type="button" class="lb-nav lb-nav--prev" aria-label="Foto anterior">'+ICON('M15 5l-7 7 7 7')+'</button><figure class="lb-fig"><img class="lb-img" alt=""><figcaption class="lb-cap"><span class="lb-count"></span><span>Render ilustrativo</span></figcaption></figure><button type="button" class="lb-nav lb-nav--next" aria-label="Foto siguiente">'+ICON('M9 5l7 7-7 7')+'</button>';document.body.appendChild(lb);lbImg=lb.querySelector('.lb-img');lbCount=lb.querySelector('.lb-count');lb.querySelector('.lb-close').addEventListener('click',lbClose);lb.querySelector('.lb-nav--prev').addEventListener('click',()=>lbStep(-1));lb.querySelector('.lb-nav--next').addEventListener('click',()=>lbStep(1));lb.addEventListener('click',e=>{if(e.target===lb||e.target.classList.contains('lb-fig'))lbClose()});document.addEventListener('keydown',e=>{if(!lb.classList.contains('is-open'))return;if(e.key==='Escape')lbClose();else if(e.key==='ArrowLeft')lbStep(-1);else if(e.key==='ArrowRight')lbStep(1)});let sx=null;lb.addEventListener('touchstart',e=>{sx=e.touches[0].clientX},{passive:true});lb.addEventListener('touchend',e=>{if(sx===null)return;const dx=e.changedTouches[0].clientX-sx;sx=null;if(Math.abs(dx)>50)lbStep(dx<0?1:-1)},{passive:true})};
const lbOpen=(imgs,i)=>{if(!lb)lbBuild();lbList=imgs.map(m=>({src:m.currentSrc||m.src,alt:m.alt}));lbIdx=i;lbPrevFocus=document.activeElement;lbShow();lb.classList.add('is-open');document.body.classList.add('lb-open');lb.querySelector('.lb-close').focus()};

document.querySelectorAll('[data-slides]').forEach(el=>{const list=(el.dataset.slides||'').split(',').map(s=>s.trim()).filter(Boolean);if(!list.length)return;const folder=el.dataset.folder||'',track=document.createElement('div');track.className='car-track';list.forEach((n,i)=>{const im=new Image();im.src=folder+n;im.alt=el.dataset.alt||'';im.loading=i?'lazy':'eager';im.decoding='async';im.addEventListener('error',()=>{im.remove();if(!track.children.length){el.classList.remove('has-images');track.remove()}});track.appendChild(im)});el.appendChild(track);el.classList.add('has-images');
track.addEventListener('click',e=>{const im=e.target.closest('img');if(!im)return;const imgs=[...track.querySelectorAll('img')];lbOpen(imgs,imgs.indexOf(im))});
if(list.length<2)return;const mk=(dir)=>{const b=document.createElement('button');b.type='button';b.className='car-btn car-btn--'+(dir<0?'prev':'next');b.setAttribute('aria-label',dir<0?'Foto anterior':'Foto siguiente');b.innerHTML=ICON(dir<0?'M15 5l-7 7 7 7':'M9 5l7 7-7 7');b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();const w=track.clientWidth,max=track.scrollWidth-w-4;if(dir>0&&track.scrollLeft>=max)track.scrollTo({left:0,behavior:'smooth'});else if(dir<0&&track.scrollLeft<=4)track.scrollTo({left:track.scrollWidth,behavior:'smooth'});else track.scrollBy({left:dir*w,behavior:'smooth'})});el.appendChild(b)};mk(-1);mk(1)})})();
